const fs=require('fs'), https=require('https');
const ROOT='https://vietnam-camp-hcmc.netlify.app/';
const NT=ROOT+'nhatrang.html';
const ref=process.env.CONTEXT==='production'?'main':'update-2027-content-videos';
const r=(s,a,b)=>s.split(a).join(b);
const addBefore=(s,mark,block)=>s.includes(mark)?s.replace(mark,block+'\n'+mark):s;
const styles='<style id="field-video-styles">.field-video{padding:44px 0;background:var(--paper-2);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.field-video__box{max-width:900px;margin:0 auto}.field-video video{display:block;width:100%;background:#061728;border-radius:18px;box-shadow:var(--shadow)}.field-video__meta{margin-top:14px}.field-video__meta h3{font-size:19px}.field-video__meta p{margin:6px 0 0;color:var(--muted);font-size:13.5px}.school-life{padding:52px 0;background:#fff}.school-life .facts{margin-top:22px}</style>';
const hVideo='<section class="field-video"><div class="wrap field-video__box"><p class="eyebrow">Previous programme footage</p><video controls playsinline preload="metadata" src="/media/hcmc-tas-2026.mp4" aria-label="2026 호치민 TAS 프로그램 현장 영상"></video><div class="field-video__meta"><h3>지난 프로그램 현장 영상</h3><p>2026년 실제 프로그램에서 촬영한 영상입니다. 학교와 수업 환경을 참고해 주세요.</p></div></div></section>';
const school='<section class="school-life"><div class="wrap"><div class="sec-head"><p class="eyebrow">School life & parent updates</p><h2>학교에 있는 동안에도,<br>아이의 하루를 확인합니다.</h2><p class="lead">TAS의 디지털 학습도구와 학부모 소통 시스템을 통해 학교생활과 학습 진행 상황을 확인할 수 있습니다.</p></div><div class="facts"><div class="fact"><h4><span>Parent App</span>Toddle 학부모 앱</h4><p>학생 활동 사진, 과제, 교사 피드백과 학습 진행 상황을 학부모와 공유하는 데 활용됩니다.</p></div><div class="fact"><h4><span>Digital Learning</span>학생별 iPad 활용</h4><p>수업 자료와 디지털 학습도구를 수업과 과제에 활용합니다.</p></div><div class="fact"><h4><span>Campus Life</span>Student ID Card</h4><p>학교 출입 체크인과 Cafeteria 이용 등 캠퍼스 생활에 사용됩니다.</p></div></div></div></section>'+hVideo;
function hcmc(h){h=r(h,'https://YOUR-DOMAIN-HERE/',ROOT);h=h.replace('</head>',styles+'</head>');h=addBefore(h,'<!-- ============ DAY FLOW ============ -->',school);const needle='<div class="sup__i"><div class="ico">⛑</div><b>생활지원 전용 차량</b>';const extra='<div class="sup__i"><div class="ico">⌂</div><b>매일 객실 청소</b><p>서비스드 레지던스 하우스키핑이 매일 진행되어 장기 체류 중 객실 관리 부담을 줄입니다.</p></div><div class="sup__i"><div class="ico">○</div><b>학부모 여가 안내</b><p>골프·테니스·요가 등 현지 활동과 예약 정보를 안내합니다.</p></div><div class="sup__i"><div class="ico">◇</div><b>주말 가족 일정 지원</b><p>주말 가족여행과 골프 등 선택 일정의 예약과 이용 정보를 지원합니다.</p></div>';const p=h.indexOf(needle);if(p>=0){const end=h.indexOf('</div>',h.indexOf('</p>',p))+6;h=h.slice(0,end)+extra+h.slice(end);}return h;}
const nVideos='<section class="field-video"><div class="wrap field-video__box"><p class="eyebrow">Previous programme footage</p><video controls playsinline preload="metadata" src="/media/nha-trang-ave-2026.mp4"></video><div class="field-video__meta"><h3>2026 나트랑 AVE 프로그램 현장</h3><p>지난 실제 프로그램에서 촬영한 영상입니다. 2027 겨울 프로그램의 학교·수업 환경 참고용입니다.</p></div></div></section><section class="field-video" style="background:#fff"><div class="wrap field-video__box"><p class="eyebrow">Previous preschool footage</p><video controls playsinline preload="metadata" src="/media/nha-trang-preschool-2026.mp4"></video><div class="field-video__meta"><h3>2026 나트랑 유아 프로그램 현장 영상</h3><p>영상에는 당시 운영 브랜드가 표시될 수 있으며, 현재 2027 Kid Castle 프로그램의 수업 환경 참고 자료입니다.</p></div></div></section>';
const nSupport='<section class="school-life"><div class="wrap"><div class="sec-head"><p class="eyebrow">Stay & family support</p><h2>아이 수업뿐 아니라,<br>가족의 2~4주 생활까지.</h2></div><div class="facts"><div class="fact"><h4><span>Housekeeping</span>주 3회 객실 청소</h4><p>Meliá Vinpearl Empire 객실은 주 3회 하우스키핑이 진행됩니다.</p></div><div class="fact"><h4><span>Help Desk</span>캠프 전용 Help Desk</h4><p>현지 생활 안내와 유료 세탁 서비스, 학교·생활 관련 문의를 지원합니다.</p></div><div class="fact"><h4><span>Transport</span>전용 스쿨버스</h4><p>자녀 등·하교에 캠프 전용 차량을 운영합니다.</p></div><div class="fact"><h4><span>Parent Programme</span>시티투어·주말 예약</h4><p>학부모 주 1회 시티투어와 주말 가족여행·골프 예약 안내를 제공합니다.</p></div></div></div></section>';
function nha(h){h=r(h,'https://YOUR-DOMAIN-HERE/nhatrang.html',NT);h=h.replace('</head>',styles+'</head>');h=r(h,'08:30 ~ 16:45','08:30 ~ 16:30');h=r(h,'08:30 ~ 15:40','08:30 ~ 15:00');h=r(h,'한 반 최대 15명 · 총 4개 반','15명 기준 · 총 4개 반 운영');h=r(h,'한 반 최대 15명','15명 기준 · 4개 반 운영');h=r(h,'한 반 정원은 최대 15명입니다.','15명 기준으로 총 4개 반을 운영하며, 모집 인원에 따라 반 구성은 조정될 수 있습니다.');h=r(h,'4~6세는 Kid Castle International Kindergarten으로 배정되어 08:30 ~ 15:00 운영됩니다.','4~6세(2024년생~2022년생)는 Kid Castle International Kindergarten으로 배정되어 08:30 ~ 15:00 운영됩니다. 각 반은 26명 기준이며 원어민 교사와 이중언어 현지 보조교사 2~3명이 함께 운영합니다. 기존 재학생과 같은 반에서 생활하며 캐나다 교육 프로그램을 기반으로 수업합니다.');h=addBefore(h,'<!-- ============ DAY FLOW ============ -->',nVideos);h=addBefore(h,'<!-- ============ PRICE ============ -->',nSupport);h=h.replace(/나트랑 별도 브로셔가 없어[^<\n]*/g,'');return h;}
function get(url){return new Promise((ok,no)=>https.get(url,{headers:{'User-Agent':'TNS-Netlify-Build'}},res=>{if(res.statusCode!==200){no(new Error('HTTP '+res.statusCode+' '+url));return}let d='';res.setEncoding('utf8');res.on('data',c=>d+=c);res.on('end',()=>ok(d));}).on('error',no));}
(async()=>{let h=fs.readFileSync('index.html','utf8');fs.writeFileSync('index.html',hcmc(h));const raw=await get('https://raw.githubusercontent.com/tnsuhak/Vietnam_Camp_NT/'+ref+'/index.html');fs.writeFileSync('nhatrang.html',nha(raw));fs.writeFileSync('robots.txt','User-agent: *\nAllow: /\n\nSitemap: '+ROOT+'sitemap.xml\n');fs.writeFileSync('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>'+ROOT+'</loc><lastmod>2026-08-30</lastmod></url><url><loc>'+NT+'</loc><lastmod>2026-08-30</lastmod></url></urlset>');console.log('safe patch complete',ref);})().catch(e=>{console.error(e);process.exit(1)});
